### ISSUE TITLE
Disconnect from CloudFlare

### ISSUE THREAD

**Issue by merelinguist** [Prog-Soc/site#1]
With the new modern JS stack, cloudflare caching and the scripts it imports are somewhat redundant, or even slowing the site down. Do you think you could just point the domain towards Netlify? Thanks :)

**Comment by Gunner237** [comment]
Not convinced about speed benefits. I have set up ww1.progsoc.online pointing to the same site but without Cloudflare intervention so I can do some comparisons on other computers.
Ready to eat humble pie if Netlify is faster...

**Comment by Gunner237** [comment]
Update: Netlify does appear to be faster off the bat. I'm wondering whether this is to do with Google Analytics, rather than Cloudflare? Do we still want Analytics?

**Comment by merelinguist** [comment]
If we still want GA, I can implement that into our own code, but I think it's okay without for now. 👍

**Comment by merelinguist** [comment]
BTW, the main problem is that CF scripts are render-blocking, which I can fix "natively", but not with on CF.

**Comment by Gunner237** [comment]
Kk. Will sort out later this week. Give me a nudge if I haven't done by Sun.

**Comment by merelinguist** [comment]
Okay, perfect, thank you!! 😄
